### ISSUE TITLE
Spotlight coloring issues depending on camera distance

### ISSUE THREAD

**Issue by Jokler** [naasblod/bevy_contact_projective_decals#11]
Replace the point light in the static example with this:
```rust
commands.spawn(SpotLightBundle {
    spot_light: SpotLight {
        shadows_enabled: true,
        intensity: 5000000.0,
        ..Default::default()
    },
    transform: Transform::from_xyz(0.0, 1.8, 4.0),
    ..Default::default()
});
```

![The Issue](https://github.com/user-attachments/assets/b9a36776-d96e-4f00-95f1-9ed7d1a425b0)
As you get closer the issue disappears, moving away it turns completely black.
The issue seems to be caused by `normal_depth` in the shader because it disappears when I replace it with `in.world_position.w` but I don't understand the code generating that or what it's purpose is.

**Comment by naasblod** [comment]
Looking into it, thanks!

**Comment by naasblod** [comment]
Ok I don't really understand either. But it makes sense to have `in.world_position.w` there instead of `normal_depth` since that's the projected depth normal's length is dependent on camera positioning while the pbr input just wants the world_position of the texel(?). So `normal_depth` is probably wrong.

Thanks! I've updated `main`
